import os

# APA_FILE_PATH = os.environ.get('APA_FILE_PATH')
# APA_WITH_CUSTOM_IDS = os.environ.get('APA_WITH_CUSTOM_IDS')
# APA_PRIAME_ZIADOSTI = os.environ.get('APA_PRIAME_ZIADOSTI')
# APA_ZIADOSTI_O_DIELY = os.environ.get('APA_ZIADOSTI_O_DIELY')
# APA_ZIADOSTI_O_PROJEKTOVE_PODPORY = os.environ.get('APA_ZIADOSTI_O_PROJEKTOVE_PODPORY')
DATABASE_URL = os.environ.get('DATABASE_URL')
ELASTIC_HOST = os.environ.get('ELASTIC_HOST')
ELASTIC_PORT = int(os.environ.get('ELASTIC_PORT', 9200))
SQL_FOLDER = 'sql/'


APA_PRIJIMATELIA = os.environ.get('APA_PRIJIMATELIA')
APA_ZIADOSTI_O_PROJEKTOVE_PODPORY = os.environ.get('APA_ZIADOSTI_O_PROJEKTOVE_PODPORY')
APA_ZIADOSTI_O_PRIAME_PODPORY = os.environ.get('APA_ZIADOSTI_O_PRIAME_PODPORY')
APA_ZIADOSTI_O_PRIAME_PODPORY_DIELY = os.environ.get('APA_ZIADOSTI_O_PRIAME_PODPORY_DIELY')

