import os

APA_FILE_PATH = os.environ.get('APA_FILE_PATH')
APA_WITH_CUSTOM_IDS = os.environ.get('APA_WITH_CUSTOM_IDS')
APA_PRIAME_ZIADOSTI = os.environ.get('APA_PRIAME_ZIADOSTI')
APA_ZIADOSTI_O_DIELY = os.environ.get('APA_ZIADOSTI_O_DIELY')
APA_ZIADOSTI_O_PROJEKTOVE_PODPORY = os.environ.get('APA_ZIADOSTI_O_PROJEKTOVE_PODPORY')
DATABASE_URL = os.environ.get('DATABASE_URL')
SQL_FOLDER = 'sql/'
